name: 'planetkart'
version: '1.0.0'

profile: 'planetkart'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  planetkart:
    staging:
      +materialized: view
      +schema: PLANETKART_STAGE
    marts:
      +materialized: table
      +schema: PLANETKART_ANALYTICS

snapshots:
  planetkart:
    +target_schema: stage
    +strategy: timestamp
    +updated_at: updated_at