version: 2

sources:
  - name: raw
    description: Raw data from PlanetKart systems
    database: a_database
    schema: planetkart_raw
    tables:
      - name: customers
        description: Customer master data
        columns:
          - name: customer_id
            description: Unique customer identifier
            tests:
              - unique
              - not_null
      - name: products
        description: Product catalog
        columns:
          - name: product_id
            tests:
              - unique
              - not_null
      - name: regions
        description: Delivery regions
        columns:
          - name: region_id
            tests:
              - unique
              - not_null
      - name: orders
        description: Order transactions
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
      - name: order_items
        description: Order line items